In [22]:
import numpy as np

arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2 = arr.ravel().copy()
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr2[0] = 10
arr2

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
def solution(n):
    answer = ''
    for i in range(1, n + 1):
        if i % 2 == 0:
            answer += '박'
        else:
            answer += '수'
    return answer

solution(3)

'수박수'