# 생성 및 초기화

- np.zeros()
- np.ones()
- np.full()
- np.eye()
- np.empty()

## np.zeros(shape, dtype=float)

- 지정된 구조의 배열을 생성하고 모든 요소를 0으로 초기화
- shape: tuple 형태로 행, 열 지정
- dtype: 데이터 타입 지정. 기본값은 numpy.float64

In [4]:
import numpy as np

def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [5]:
# 3행 4열 구조 안에 모든 값이 0으로 채워짐
# 구조는 튜플에 묶어 넘김
arr = np.zeros((3,4))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# dtype만 int로 바꿔서 생성
arr = np.zeros((3,4), dtype=int)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int64
    array data : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## np.ones(shape, dtype=float)

- 지정한 구조로 배열을 생성하고 모든 요소를 1로 초기화
- shape: tuple 형태로 행, 열 지정
- dtype: 데이터 타입 지정. 기본값은 numpy.float64

In [7]:
# 3행 4열 구조. 초기값은 모두 1
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## np.full(shape, fill_value, dtype)

- 지정한 구조로 배열을 생성하고 모든 요소를 fill_value로 초기화
- shape: tuple 형태로 행, 열 지정
- dtype: 데이터 타입 지정. 기본값은 들어오는 데이터의 자료형

In [8]:
# 3행 4열 구조 안에서 초기값을 5로 가지는 배열

arr = np.full((3, 4), 5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int64
    array data : 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


# np.eye(n, M=None, dtype=float)

- (N, M) 구조로 단위 행렬을 생성
- M: 열 개수를 지정, 기본값 = N
- dtype: 데이터 타입 지정. 기본값 = numpy.float64

In [9]:
# 3행 3열의 단위행렬
arr = np.eye(3)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# row 5, column 3 인 단위행렬 .eye()로 만들기

arr = np.eye(5,3)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5, 3)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


## np.empty(shape, dtype=float)

- 직전 메모리에 저장된 값을 사용
- 배열을 생성하는 데 가장 빠르고 효율적인 방법
- shape: tuple type으로 행, 열 구조 지정
- dtype: 데이터 타입 지정. 기본값 numpy.float64

In [11]:
# 직전의 메모리 저장값을 사용하기 위해 직전에 만들었던 것과 동일한 shape 배열 생성
# 7 * 2
arr = np.empty((7,2))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (7, 2)
    ndim : 2
    dtype : float64
    array data : 
 [[4.64250099e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [12]:
# 3 * 4 구조로 다시 만들자

arr = np.empty((3,4))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# like 함수

- 전달받은 배열과 동일한 shape로 초기값을 설정하여 새로운 배열 생성
- np.zeros_like(): 초기값 0인 배열 생성
- np.ones_like(): 초기값 1인 배열 생성
- np.full_like(): 초기값 fill_value인 배열 생성

In [13]:
# ones_like()
# 2행 3열 구조에서 1~6으로 구성된 배열

data = [[1,2,3],
        [4,5,6]]
arr = np.array(data)
np_print(arr)
arr1 = np.ones_like(arr)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int64
    array data : 
 [[1 2 3]
 [4 5 6]]

    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int64
    array data : 
 [[1 1 1]
 [1 1 1]]
