# 범위와 조건이 있는 데이터를 가지는 1차원 배열 생성

- np.linspace()
- np.arange()
- np.logspace()

## np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

- 시작값(start)부터 마지막값(stop) 사이의 범위에서 균등한 간격으로 일정 개수(num)개의 데이터를 가지는 배열 생성
- num : 데이터 개수, 기본값 = 50
- endpoint : 마지막값에 stop을 포함/제외하는 조건 지정, 기본값 = True(포함)
- retstep : True로 전달하면 (배열, 데이터 사이의 간격)의 데이터를 담은 tuple을 반환
- dtype : 배열의 데이터 타입을 지정, 기본값 = None

In [1]:
import numpy as np

def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [6]:
# 0 이상 1 이하의 범위에서 발생한 숫자 5개를 포함하는 배열
arr = np.linspace(0, 1, num=5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : float64
    array data : 
 [0.   0.25 0.5  0.75 1.  ]


In [7]:
# endpoint = False -> endpoint 포함 안 함
arr = np.linspace(0, 1, num=5, endpoint=False)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : float64
    array data : 
 [0.  0.2 0.4 0.6 0.8]


In [9]:
# retstep 설정 -> 반환값 tuple -> (배열객체, 간격값)

arr = np.linspace(0, 1, num=5, retstep=True)
print(arr)

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)


## np.arange(start=0, stop, step=1,  dtype=None)

- 시작값(start)부터 마지막값(stop) 사이의 범위에서 지정한 간격(step)으로 일정 개수(num)개의 데이터를 가지는 배열 생성
- 파이썬 내장함수 range()와 유사
- start : 시작값, 기본값 = 0
- stop : 마지막값으로 범위에 포함되지 않음
- step : 데이터 사이의 간격, 기본값 = 1
- dtype : 배열의 데이터 타입을 지정, 기본값 = None

In [10]:
list(range(5))

[0, 1, 2, 3, 4]

In [11]:
# 0 이상 5 미만의 범위에서 1씩 증가하는 숫자(정수)를 가지는 배열

arr = np.arange(5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : int64
    array data : 
 [0 1 2 3 4]


In [12]:
# 시작, 끝, 간격
# 0 이상  5 미만의 범위에서 0.5씩 증가하는 숫자(정수)를 가지는 배열

arr = np.arange(0, 5, 0.5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (10,)
    ndim : 1
    dtype : float64
    array data : 
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [13]:
# arange() 메서드로 생성된 배열과 shape(1, 5)인 배열은 동일해 보이지만
# shape와 dimension이 다르다

arr = np.arange(1, 5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : int64
    array data : 
 [1 2 3 4]


In [14]:
arr = arr.reshape(1,4)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (1, 4)
    ndim : 2
    dtype : int64
    array data : 
 [[1 2 3 4]]


## np.logspace(start, stop, num=50, endpoint=True, dtype=None)

- 시작값(start)부터 마지막값(stop) 사이의 로그 스케일로 지정된 범위에서 균등한 간격으로 일정 개수(num)의 데이터를 가지는 배열 생성
- num : 데이터 개수, 기본값 = 50
- endpoint : 마지막 값에 stop을 포함/제외하는 조건 지정. 기본값 True(포함)
- dtype : 배열의 데이터 타입을 지정. 기본값 None

In [15]:
# 0 이상 1 이하의 범위에서 로그스케일을 적용한 값(50개)을 가지는 배열
# 밑 10인 로그 기준으로 만들어짐

arr = np.logspace(0, 1)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (50,)
    ndim : 1
    dtype : float64
    array data : 
 [ 1.          1.04811313  1.09854114  1.1513954   1.20679264  1.26485522
  1.32571137  1.38949549  1.45634848  1.52641797  1.59985872  1.67683294
  1.75751062  1.84206997  1.93069773  2.02358965  2.12095089  2.22299648
  2.32995181  2.44205309  2.55954792  2.6826958   2.8117687   2.9470517
  3.0888436   3.23745754  3.39322177  3.55648031  3.72759372  3.90693994
  4.09491506  4.29193426  4.49843267  4.71486636  4.94171336  5.17947468
  5.42867544  5.68986603  5.96362332  6.25055193  6.55128557  6.86648845
  7.19685673  7.54312006  7.90604321  8.28642773  8.68511374  9.10298178
  9.54095476 10.        ]


In [16]:
arr = np.logspace(0, 3, 4)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : float64
    array data : 
 [   1.   10.  100. 1000.]


In [17]:
# 시작, 끝, 개수 40개로 만들기
arr = np.logspace(0, 10, 40)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (40,)
    ndim : 1
    dtype : float64
    array data : 
 [1.00000000e+00 1.80472177e+00 3.25702066e+00 5.87801607e+00
 1.06081836e+01 1.91448198e+01 3.45510729e+01 6.23550734e+01
 1.12533558e+02 2.03091762e+02 3.66524124e+02 6.61474064e+02
 1.19377664e+03 2.15443469e+03 3.88815518e+03 7.01703829e+03
 1.26638017e+04 2.28546386e+04 4.12462638e+04 7.44380301e+04
 1.34339933e+05 2.42446202e+05 4.37547938e+05 7.89652287e+05
 1.42510267e+06 2.57191381e+06 4.64158883e+06 8.37677640e+06
 1.51177507e+07 2.72833338e+07 4.92388263e+07 8.88623816e+07
 1.60371874e+08 2.89426612e+08 5.22334507e+08 9.42668455e+08
 1.70125428e+09 3.07029063e+09 5.54102033e+09 1.00000000e+10]


In [18]:
# endpoint 설정

arr = np.logspace(0, 1, 40, endpoint = False)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (40,)
    ndim : 1
    dtype : float64
    array data : 
 [1.         1.05925373 1.12201845 1.18850223 1.25892541 1.33352143
 1.41253754 1.49623566 1.58489319 1.67880402 1.77827941 1.88364909
 1.99526231 2.11348904 2.23872114 2.37137371 2.51188643 2.66072506
 2.81838293 2.98538262 3.16227766 3.34965439 3.54813389 3.75837404
 3.98107171 4.21696503 4.46683592 4.73151259 5.01187234 5.30884444
 5.62341325 5.95662144 6.30957344 6.68343918 7.07945784 7.49894209
 7.94328235 8.41395142 8.91250938 9.44060876]
