## 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬

In [11]:
import numpy as np
def np_print(nparr):
    print('''
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

In [12]:
x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    dimension : 1
    dtype : int64
    data :
 [0 1 2 3 4]
    


In [13]:
# 기본 파이썬 문법으로 순번 뒤집기

x[::-1]

array([4, 3, 2, 1, 0])

In [37]:
np.random.seed(20)

In [29]:
# 오름차순 정렬
a = np.random.randint(0, 10, 5)
a

array([3, 9, 4, 6, 7])

In [30]:
# np.sort(자료) -> 원본에 반영되지 않음

np.sort(a)

array([3, 4, 6, 7, 9])

In [31]:
a

array([3, 9, 4, 6, 7])

In [32]:
# arr.sort() -> 원본 자료 변경
a.sort()
a

array([3, 4, 6, 7, 9])

In [33]:
b = np.random.randint(0, 10, 5)
b

array([2, 0, 6, 8, 5])

In [34]:
# np.argsort(array)는 내부 아이템들을 오름차순으로 정렬하기 위해 현재 몇 번 인덱스에 있는 자료를 어디에 배치해야 하는지 보여줌
# array에서 가져 올 인덱스를 출력
np.argsort(b)  # 1번 인덱스 해당값 0을 맨 앞에, 0번 인덱스 해당값 2를 두번째

array([1, 0, 4, 2, 3])

In [38]:
# 0 이상 1 미만 범위에서 무작위 실수값의 3행 3열 배열 2개 생성

a = np.random.random((3,3))
b = np.random.random((3,3))
a, b

(array([[0.5881308 , 0.89771373, 0.89153073],
        [0.81583748, 0.03588959, 0.69175758],
        [0.37868094, 0.51851095, 0.65795147]]),
 array([[0.19385022, 0.2723164 , 0.71860593],
        [0.78300361, 0.85032764, 0.77524489],
        [0.03666431, 0.11669374, 0.7512807 ]]))

## 예) 2차원 배열의 경우

- 기본값 axis = -1 <br>
- 현재 배열의 axis = 0, 1 <br>
- 마지막 axis = 1 (열별 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [39]:
# 기본 방향(axis=-1) -> 행별 정렬
print(a)
np.sort(a)

[[0.5881308  0.89771373 0.89153073]
 [0.81583748 0.03588959 0.69175758]
 [0.37868094 0.51851095 0.65795147]]


array([[0.5881308 , 0.89153073, 0.89771373],
       [0.03588959, 0.69175758, 0.81583748],
       [0.37868094, 0.51851095, 0.65795147]])

## axis = 0 (열별 정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>`

In [43]:
print(a)
np.sort(a, axis=0)

[[0.5881308  0.89771373 0.89153073]
 [0.81583748 0.03588959 0.69175758]
 [0.37868094 0.51851095 0.65795147]]


array([[0.37868094, 0.03588959, 0.65795147],
       [0.5881308 , 0.51851095, 0.69175758],
       [0.81583748, 0.89771373, 0.89153073]])