## 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱 : 하나의 요소에 대해 참조

- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개
- 인덱싱으로 참조한 요소에 대해 수정 가능
- 인덱스 배열을 전달하여 여러 개의 요소 참조


In [1]:
import numpy as np
def np_print(nparr):
    print('''
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

In [2]:
# 0부터 23까지 1씩 증가하는 값을 가지는 1차원 배열 생성

arr1 = np.arange(0, 24)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (24,)
    dimension : 1
    dtype : int64
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [3]:
# 1차원 배열 인덱싱 : 1번 인덱스 요소 접근
arr1[1]

1

In [4]:
# 마지막 요소 접근

arr1[-1]

23

In [5]:
# 1차원 배열 인덱싱으로 값 수정

arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [6]:
# arr1을 이용해 4 x 6 형태의 2차원 배열 arr2 만들기

arr2 = arr1.reshape(4, 6)
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22, 100]])

In [7]:
# 2차원 배열 인덱싱 : 2차원배열[행인덱스, (열인덱스)]
# 하나의 행에 접근: 1행
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr2[1][3]

9

In [9]:
# 각 열에 접근
# 반환값 : 1d array

arr2[:, 1] # 2번째 열 반환

array([ 1,  7, 13, 19])

In [10]:
arr2[2, 2]

14

In [11]:
# 여러 행 조회
arr2[[0, 3]]

array([[  0,   1,   2,   3,   4,   5],
       [ 18,  19,  20,  21,  22, 100]])

In [12]:
# 여러 열 조회

arr2[:, [0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [19]:
# 0, 2 번째 행의 3, 5 번째 열 가져오기

arr2[[0,2]][:, [3,5]]

array([[ 3,  5],
       [15, 17]])

In [20]:
# 2차원 배열 인덱싱을 통한 값 수정
# 하나의 행/열을 모두 동일한 값으로 수정: 전달하는 값은 스칼라
# 서로 다른 값으로 수정: 배열 구조에 맞춰 자료 전달

# 하나의 값으로 수정하는 예시
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [21]:
# 여러 값 대입
arr2[1] = [9, 9, 9, 99, 99, 99]
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [22]:
# 3차원 배열
# 구조: 2개의 층(페이지, 면), 
# np.arange()

arr3 = np.arange(0, 24).reshape((2,4,3))
np_print(arr3)


    type : <class 'numpy.ndarray'>
    shape : (2, 4, 3)
    dimension : 3
    dtype : int64
    data :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
    


In [23]:
# 3차원 배열 인덱싱 : arr[면, 행, 열]
# 0번째 면(페이지) 접근

arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
# 첫 번째 면, 1번 행 접근
arr3[0][1], arr3[0,1]

(array([3, 4, 5]), array([3, 4, 5]))

In [26]:
# 첫 번째 면, 1번 행, 0번 열에 접근

arr3[0,1,0]

3

In [28]:
# 3차원 배열도 배열 인덱싱으로 값 수정 가능
# 스칼라 연산으로 동일한 값으로 수정
#
arr3[1] = 0
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [29]:
# 1번 면 1번 행을 [1,2,3]으로 바꾸기

arr3[1,1] = [1,2,3]
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [31]:
# 여러 개의 인덱싱을 배열로 전달
# 3차원 배열일 경우 : [페이지, [[0,1,2],[0,1,2]]]
# arr3[면, 행, 열] -> 여러 단위를 조회할 때 이중 리스트로 입력
# 삼중리스트 입력시 이중리스트 요소 반복
print(arr3)
arr3[0, [[0,1,2], [0,2,3]]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 0  0  0]
  [ 0  0  0]]]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 0,  1,  2],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

## 2. 슬라이싱 : 여러 개의 요소에 대해 참조

- axis 별로 범위 지정
    - from_index : 시작 인덱스(포함), 0일 경우 생략 가능
    - to_index : 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step : 연속되지 않은 범위의 경우 간격 지정
- 열만 조회하는 경우 : 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

In [33]:
a = np.arange(0, 24)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (24,)
    dimension : 1
    dtype : int64
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [34]:
# 1차원 배열 슬라이싱
a[1:5]

array([1, 2, 3, 4])

In [37]:
# 1번 인덱스부터 14번째 인덱스까지 2개씩 건너뛰며 접근

a[1: 15: 2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [38]:
b = a.reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
# 행 
b[0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
# 열
b[1:5, 2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [50]:
b[1:5, [2,3]]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [51]:
# 2차원 배열 슬라이싱으로 값 수정

s_arr = b[1:5, 2:4]
s_arr

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [52]:
# 0번째 행과 마지막 열을 제외한 모든 값을 99로 수정
s_arr[1:, :-1] = 99
s_arr

array([[ 6,  7],
       [99, 11],
       [99, 15],
       [99, 19]])

In [53]:
# 얕은 복사로 인한 원본 배열의 변경
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [54]:
# 연속되지 않은 범위 열 인덱싱
# 전체 행
# 1, 3번째 열

b[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

## 연습문제

- 아래 정보는 학생들의 학번, 영어 성적, 국어 성적, 수학 성적 정보 입니다.
- 영어 성적을 기준으로 각 열(column)을 정렬하세요.(오름차순)
- 즉, 영어 성적이 가장 낮은 학생이 1열, 가장 높은 학생이 마지막 열에 배치

<img src='img/sort_q1.PNG' align='left'>

In [65]:
data = [[1, 2, 3, 4],
       [70, 97, 45, 56],
       [87, 84, 33, 67],
       [46, 80, 75, 78]]
arr = np.array(data)

In [66]:
sort_order = np.argsort(arr[1])
arr[:, sort_order ]

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])

## 조건 색인(Boolean indexing)

- 배열 요소에 조건을 적용해서 True, False 반환
- True에 해당하는 요소만 조회하여 조건에 만족하는 결과 반환

In [67]:
# 스칼라 연산 이용해 10보다 큰 요소 조회
b > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
# 자료[자료를 포함한 조건식]

b[b>10]

array([99, 11, 12, 13, 99, 15, 16, 17, 99, 19, 20, 21, 22, 23])

In [71]:
b[b>10].size

14

In [81]:
# 조건색인을 이용해 b에서 짝수인 자료만 남기기
# 조건에 2개 이상의 조건을 걸때는 각 조건을 ( ) 로 감싸고
# &, | 로 연결

b[ (b%2 == 0) ][b[ (b%2 == 0) ] > 0]

array([ 2,  4,  6,  8, 12, 16, 20, 22])

In [84]:
b[ (b%2 == 0) & (b!=0)]

array([ 2,  4,  6,  8, 12, 16, 20, 22])

## 연습문제

- 조건색인을 활용해 공무원시험의 합격자 평균을 구해주세요.
- 합격점수는 60점 이상입니다.
- 아래는 시험 점수 결과입니다.<br>

[31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,55, 56, 51]

In [90]:
a = np.array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,55, 56, 51])
a[a >= 60].mean()

77.33333333333333

## 배열 복사

- 인덱싱, 슬라이싱으로 반환된 배열은 원본 배열에 종속적인 객체
- 원본과 독립된 복사본 생성 -> arr.copy() / np.copy(arr

In [91]:
arr1 = np.arange(0, 4).reshape(2,2)
arr1

array([[0, 1],
       [2, 3]])

In [93]:
arr2 = arr1.copy()
arr3 = arr1

In [94]:
arr2[0,0] = 100
arr2

array([[100,   1],
       [  2,   3]])

In [95]:
arr1

array([[0, 1],
       [2, 3]])

In [96]:
arr3[0,0] = 500
arr3

array([[500,   1],
       [  2,   3]])

In [97]:
arr1

array([[500,   1],
       [  2,   3]])