# 배열 변환

## 1. 전치(Transpose)

- 배열의 행/열 인덱스가 바뀌는 변환
- 배열객체.T : 행/열 인덱스가 바뀐 새로운 배열을 반환하며 원본은 변경되지 않음

<img src='img/transpose.PNG' width='200' height='200' align='left'>

In [1]:
import numpy as np

arr1 = np.arange(1, 13).reshape(3, 4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [2]:
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 2. 배열 형태 변경

- arr.ravel(), np.ravel(arr)
    - 다차원 배열을 1차원 배열로 변환
    - np.ravel() : 1차원으로 변환되는 결과는 원본 배열에 반영되지 않음
    - arr.ravel() : 1차원으로 변환하는 배열의 요소가 변경되면 원본 배열에도 반영됨
- arr.reshape(new_shape), np.reshape(arr, new_shape)
    - 원본 배열 객체의 구조(shape)를 변경
    - 변경하려는 구조의 전체 요소 개수와 원본 배열의 전체 요소 개수가 동일해야 함
    - 변경하려는 구조의 튜플 중 하나의 원소는 -1로 대체할 수 있고 다른 하나의 원소를 기준으로 계산되어 사용됨
    - reshape() 메서드가 반환하는 배열의 요소가 변경되면 원본 배열에도 반영됨

In [4]:
arr2 = arr1.ravel()
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
arr2[0] = 10
arr1

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
# -1 사용
arr3 = arr1.reshape(-1, 2)
arr3

array([[10,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
# 변환 후 값 수정, 원본과 비교
arr3[0] = [100, 200]

In [8]:
arr1

array([[100, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

## 3. 요소 변경, 추가, 삭제

1) 요소 변경

- arr.resize(new_shape), np.resize(arr, new_shape)
    - 배열 메서드를 사용하면 원본 변경, np 함수를 사용하면 새로운 배열 반환
    - 배열의 구조(shape)를 변경하며 원본 배열의 요소 수와 동일하지 않아도 변경 가능
    - 변경되는 배열의 요소 수가 동일할 경우 : reshape() 메서드와 동일한 결과
    - 변경되는 배열의 요소 수가 더 많을 경우
        - np.resize(arr, new_shape) : 원본을 변경하지 않고, 모자란 부분을 기존 배열 값에서 복사해서 추가
        - arr.resize(new_shape) : 원본을 변경하고, 모자란 부분을 0으로 채움
        - 공통적으로 new_shape은 튜플로 추가
    - 변경되는 배열의 요소 수가 더 작을 경우 : 마지막 남은 요소 삭제

In [9]:
arr = np.random.randint(1,10,(3,5))
arr

array([[9, 3, 6, 1, 7],
       [2, 7, 5, 5, 3],
       [8, 9, 5, 1, 7]])

In [10]:
arr2 = np.random.randint(1,10,(3,5))
arr2

array([[5, 5, 9, 2, 7],
       [3, 7, 8, 4, 1],
       [6, 6, 4, 6, 6]])

In [12]:
arr.resize(5,3)
arr

array([[9, 3, 6],
       [1, 7, 2],
       [7, 5, 5],
       [3, 8, 9],
       [5, 1, 7]])

In [13]:
# 행이 모자라만 맨 앞부터 반복
arr4 = np.resize(arr, (6,3))
arr4

array([[9, 3, 6],
       [1, 7, 2],
       [7, 5, 5],
       [3, 8, 9],
       [5, 1, 7],
       [9, 3, 6]])

In [14]:
# refcheck = False => 크기가 다를 때 0으로 남는 자리 채움
arr.resize((6,3), refcheck=False)
arr

array([[9, 3, 6],
       [1, 7, 2],
       [7, 5, 5],
       [3, 8, 9],
       [5, 1, 7],
       [0, 0, 0]])

In [15]:
# 변경되는 배열의 크기가 작은 경우 마지막 요소 삭제
# 크기가 다를 경우 refcheck=False를 반드시 넣는다.
arr.resize((3,3), refcheck=False)
arr

array([[9, 3, 6],
       [1, 7, 2],
       [7, 5, 5]])

In [16]:
arr.resize((2,2))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

## 요소 추가

- np.append(arr, values, axis=None)
    - arr 마지막에 values를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 결합
    - axis = 0 : 행 방향으로 결합 (단, 열의 개수가 동일해야 함)
    - axis = 1 : 열 방향으로 결합 (단, 행의 개수가 동일해야 함)
    - 원본 배열들에 반영되지 않음

In [17]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(1, 10).reshape(3, 3)
a, b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [18]:
# 2개 배열 결합
# axis 미지정 : np.append(arr1, arr2) => axis = None
# arr1, arr2 모두 1차원으로 변형해서 추가
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.append(a, b, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.append(a, b, axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [21]:
np.append(a, b, axis=-1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [22]:
# 열 개수가 다른 배열과 결합
# 크기가 같은 방향으로만 결합 가능
c = np.arange(30, 45).reshape(3,5)
c

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [23]:
np.append(a, c, axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [24]:
np.append(a,c, axis=1)

array([[ 1,  2,  3, 30, 31, 32, 33, 34],
       [ 4,  5,  6, 35, 36, 37, 38, 39],
       [ 7,  8,  9, 40, 41, 42, 43, 44]])

In [25]:
# 행 단위로 결합할 수 있는 구조로 변경(resize)
c.resize((5,3))
c

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [26]:
# 행 개수가 다른 배열과 결합

d = np.arange(90, 102).reshape(4,3)
d

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101]])

In [27]:
np.append(b, d, axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101]])

- np.insert(arr, idx, values, axis=None)
    - 지정한 인덱스(idx)에 value를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열의 변형되고 해당 인덱스에 추가
    - axis = 0 : 행 방향으로 n번째 행에 추가
    - axis = 1 : 열 방향으로 n번째 열에 추가
    - 원본 배열에 반영되지 않음

In [28]:
arr = np.arange(1, 10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# axis를 지정하지 않으면 arr를 1차원으로 변형한 후 변형된 배열의 지정 index에 값 추가
# 2d array를 1d array로 변형, 1번 인덱스에 100 추가

np.insert(arr, 1, 100)

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [30]:
# axis=0 : 행 방향으로 index번째 행 추가
# a 배열의 1번 인덱스 행에 100 추가 => 행의 요소 개수(열 개수)만큼 100이 추가됨
np.insert(arr, 1, 100, axis=0)

array([[  1,   2,   3],
       [100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [32]:
# axis=1 : 엷 방향으로 index 번째 열 추가
# a 배열의 2번 인덱스 열에 200 추가

np.insert(arr, 2, 200, axis=1)

array([[  1,   2, 200,   3],
       [  4,   5, 200,   6],
       [  7,   8, 200,   9]])

In [33]:
# 요소마다 다른 값으로 행/열 추가
# 요소의 개수를 동일하게 작성 -> 축을 기준으로 요소 개수 결정
np.insert(arr, 2, [10, 20, 30], axis=1)

array([[ 1,  2, 10,  3],
       [ 4,  5, 20,  6],
       [ 7,  8, 30,  9]])

3) 요소 삭제
- np.delete(arr, idx, axis=None)
    - 지정한 인덱스(idx)에 해당하는 요소를 삭제
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 해당 인덱스에 해당하는 요소를 삭제
    - axis = 0 : 행 방향으로 n번째 행을 삭제
    - axis = 1 : 열 방향으로 n번째 열을 삭제
    - 원본 배열에 반영되지 않음

In [39]:
# axis 지정 안 하는 경우 : 1차원 배열로 변환 -> 지정한 index 해당 요소 삭제
np.delete(a, 1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# 원본은 변경되지 않음
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# a 배열 세로축으로 0번째 삭제
np.delete(a, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [42]:
# a 배열 가로축으로 0번째 삭제
np.delete(a, 0, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

4) 배열 결합
- np.concatenate((arr1, arr2, ...), axis=0)
    - axis = 0(기본값) : 행 방향으로 두 배열 결합 (단, 열의 개수가 동일)
    - axis = 1 : 열 방향으로 두 배열 결합 (단, 행의 개수가 동일)
    - 원본 배열들은 변경되지 않음

In [43]:
# 1이상 7미만의 범위에서 1씩 증가하는 숫자로 2 x 3 구조의 배열 a 생성
# 7이상 13미만의 범위에서 1씩 증가하는 숫자로 2 x 3 구조의 배열 b 생성
# 13이상 23미만의 범위에서 1씩 증가하는 숫자로 2 x 5 구조의 배열 c 생성(열개수 다름)
# 23이상 38미만의 범위에서 1씩 증가하는 숫자로 5 x 3 구조읩 배열 d 생성(행개수 다름)
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
c = np.arange(13, 23).reshape(2, 5)
d = np.arange(23, 38).reshape(5, 3)

In [44]:
print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[13 14 15 16 17]
 [18 19 20 21 22]]

[[23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]



In [45]:
# axis= 0(기본값) : 행 방향으로 두 배열 결합
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
# axis = 1 : 열 방향으로 두 배열 결합
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [47]:
np.concatenate((a,c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [48]:
np.concatenate((a,c), axis=1)

array([[ 1,  2,  3, 13, 14, 15, 16, 17],
       [ 4,  5,  6, 18, 19, 20, 21, 22]])

In [49]:
# 열 방향으로 결합 : 행 개수 동일
np.concatenate((a,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

- np.split(arr, indices_or_sections, axis=0)
    - axis = 0(기본값) : 행 단위로 분리
    - axis = 1 : 열 단위로 분리
    - 원본 배열은 변경되지 않음

In [50]:
a = np.arange(1, 37).reshape(6, 6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [51]:
# 균등하지 않게 행 기준으로 분리 : 분리할 인덱스 지점 입력
# 리스트로 넘기면 위치를 지정
# 스칼라를 넘기면 균등하게 개수를 맞춰 쪼갬 -> 나눈 개수가 정수로 떨어져야 함

np.split(a, [1, 2, 3], axis=0)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [52]:
np.split(a, 2, axis=0)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [53]:
np.split(a, 4, axis=0)

ValueError: array split does not result in an equal division

In [54]:
# 열 방향으로 균등하게 분리
np.split(a, 3, axis=1)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]