In [1]:
# 라이브러리 불러오기
import numpy as np

In [2]:
# Numpy 객체 정보를 확인하기 위한 사용자 함수 정의 : 객체타입, 구조, 차원, 데이터타입
def np_print(arr):
    text="""
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data : \n {}""".format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

## 산술연산

- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 : /, divide()
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) : dot()

In [5]:
# 1부터 10미만의 범위(지정범위)에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열의 배열
a = np.arange(1, 10).reshape(3, 3)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# 4이상 13미만의 범위에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열 배열 생성
b = np.arange(4, 13).reshape(3, 3)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# 10~21까지 3행 4열 형태로 만들기
c = np.arange(10, 22).reshape(3, 4)
np_print(c)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    dimension : 2
    dtype : int32
    data : 
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### 더하기
    - 배열 + 배열
    - np.add(arr1, arr2)

In [9]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
# 산술 연산자
a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [11]:
np.add(a, b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [12]:
# 구조 다른 배열간의 산술연산시 에러 발생(+)
a + c

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### 빼기

    - 배열 - 배열
    - np.subtract(arr1, arr2)

In [13]:
# 산술연산자
a - b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [14]:
b - a

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [15]:
# 메서드 활용
np.subtract(a, b)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [16]:
np.subtract(b, a)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### 나누기

    - 배열 / 배열
    - np.divide(arr1, arr2)

In [17]:
# 산술연산자
a / b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [18]:
b / a

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

In [19]:
# 메서드
np.divide(a, b)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [20]:
np.divide(b, a)

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

### 곱하기

    - 배열 * 배열
    - np.multiply(arr1, arr2)

In [21]:
# 산술연산자
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [22]:
b * a

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [23]:
np.multiply(a, b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [24]:
np.multiply(b, a)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

### 지수곱 표현

- 지수(exponent) : 부동 소수점으로 숫자를 표시할 때 거듭제곱을 사용하여 표현. <br>
(예) 2.14e+2 = 2.14 x 102 = 214 / 2.98e-8 = 2.98 x 10-8 = 0.0000000298
- np.exp(arr) : 밑(base)이 자연상수 e 인 지수함수로 변환(y = e**x)

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# 지수함수
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### 제곱근
- np.sqrt(arr)

<img src='img/sqrt.gif' width='400' height='200' align='left'>

In [27]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### 내적(행렬곱)

- np.dot(a, b)

<img src='img/dotProduct.png' width='400' height='200' align='left'>

In [28]:
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [29]:
np.dot(a, b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

In [30]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Numpy 배열 연산

#### 2. 비교 연산

1) 요소
- 값에 대한 비교 : ==, !=
- 크기에 대한 비교 : >, <, >=, <=

2) 배열
- 두 배열 전체에 대한 비교 : array_equal(a, b)

In [31]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
# 두 배열 요소에 대하여 값이 동일한지를 비교
# 반환 : 각 요소마다의 비교결과(T/F)가 배열로 표현됨
a == b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [33]:
a != b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [34]:
# 두 배열 요소에 대해 크기 비교
a < b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
# 두 배열이 완전히 일치하는지 여부만 조회
# 하나의 True/False로 반환
np.array_equal(a, b)

False

### Numpy 배열 연산

3. 집계 함수

    - Numpy 배열에 대해 집계 함수를 적용할 때는 반드시 axis로 설정된 기준에 따라 연산 수행
    - 별도로 값을 지정하지 않으면 기본값은 axis = None으로 지정
    - axis
        - axis = None <br>
        전체 데이터를 하나의 배열로 간주하고 집계 함수의 연산 범위를 전체 배열로 지정
        <br>
        <img src='img/axis_None.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 0 <br>
        열을 기준으로 동일한 열에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_0.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 1 <br>
        행을 기준으로 동일한 행에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_1.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
    - 집계 함수 : 배열객체에 대한 메소드로 사용하거나 Numpy 라이브러리의 메소드로 사용하는 두 가지 방법
        - 합계 : sum()
        - 최소값 : min()
        - 최대값 : max()
        - 누적 합계 : cumsum()
        - 평균 : mean()
        - 중앙값 : median()
            - 크기 순으로 나열된 데이터에 대해 중앙에 위치하는 값
        - 상관계수 : corrcoef()
            - 데이터 간의 상관관계를 나타내는 수치(-1 <= r <= 1)
        - 표준편차 : std()
            - 분산의 제곱근, 데이터가 평균으로부터 흩어져 있는 정도
            - 분산 = 편차(요소-전체평균)제곱의 평균
        - 고유값 : unique()

In [38]:
#사용할 배열 객체 확인
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
# 합계 - 전체 기준 => 모든 요소에 대한 합
# 1) 배열 타입의 메서드 : arr.sum()
# 2) numpy 함수 : np.sum(arr)
a.sum()

45

In [40]:
np.sum(a)

45

In [41]:
# 합계 - row, 가로축별 합산
# 메서드, np함수의 파라미터값 : axis=1
# 결과값 : [0번 row의 합, 1번 row의 합, 2번 row의 합...]
print(c.sum(axis=1))
print(c)

[46 62 78]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [43]:
# 합계 - column, 세로축별 합산 결과
# 메서드, np함수의 파라미터값 : axis=0
# 결과값 : [0번째 column합, 1번째 column합, 2번째 column합....]
print(c.sum(axis=0))
print(c)

[42 45 48 51]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [45]:
# 최소값 - 전체 기준
# 1) 배열 타입의 메서드 : arr.min()
# 2) numpy 함수 : np.min(arr)
c.min()
np.min(c)

10

In [46]:
# (참고) 파이썬 리스트에서 최소값 찾기
x = [1, 2, 3, 4]
min(x)

1

In [47]:
# 최소값 - 각 가로축(row)별 최소값 찾기
# 결과값 : [0번째row 최소값, 1번째row 최소값...]
print(c.min(axis=1))
print(c)
print(np.min(c, axis=1))

[10 14 18]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 14 18]


In [48]:
# 최소값 - 각 세로축(column)별 최소값 찾기
# 결과값 : [0번째colunm 최소값, 1번째column 최소값...]
print(c.min(axis=0))
print(np.min(c, axis=0))

[10 11 12 13]
[10 11 12 13]


In [50]:
# 최대값 - 전체기준
# 1) 배열 타입의 메서드 : arr.max()
# 2) numpy함수 : np.max(arr)
c.max()
np.max(c)

21

In [51]:
# 최대값 - 가로축 기준(row)
c.max(axis=1)

array([13, 17, 21])

In [52]:
# 최대값 - 세로축 기준(column)
np.max(c, axis=0)

array([18, 19, 20, 21])

In [53]:
# 누적합계 - 전체 기준
# 1) 배열 타입의 메서드 : c.cumsum()
# 2) numpy 함수 : np.cumsum()
# 결과값 : 
c.sum()

186

In [54]:
c.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145, 165, 186],
      dtype=int32)

In [57]:
# 누적합계 - 가로축(row) 기준
print(c.cumsum(axis=1))
print(c)
print(np.cumsum(c, axis=1))

[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]


In [59]:
# 누적합계 - 세로축 기준
print(c.cumsum(axis=0))
print(np.cumsum(c, axis=0))

[[10 11 12 13]
 [24 26 28 30]
 [42 45 48 51]]
[[10 11 12 13]
 [24 26 28 30]
 [42 45 48 51]]


In [61]:
# 평균 - 전체 기준
# 1) 배열 타입의 메서드 : arr.mean()
# 2) numpy 함수 : np.mean(arr)
print(c.mean())
print(np.mean(c))

15.5
15.5


In [63]:
# 평균 - 가로축 기준
print(c.mean(axis=1))
print(np.mean(c, axis=1))

[11.5 15.5 19.5]
[11.5 15.5 19.5]


In [64]:
# 평균 - 세로축 기준
print(c.mean(axis=0))
print(np.mean(c, axis=0))

[14. 15. 16. 17.]
[14. 15. 16. 17.]


In [65]:
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [66]:
# 중앙값 - 전체 기준
# numpy 함수 : np.median()
# arr.median()을 쓸 수 없음
# c.median()불가능
np.median(c)

15.5

In [67]:
# 중앙값 - 가로축 기준
np.median(c, axis=1)

array([11.5, 15.5, 19.5])

In [68]:
# 중앙값 - 세로축 기준
np.median(c, axis=0)

array([14., 15., 16., 17.])

In [70]:
# 상관계수 : 두 데이터간의 상관관계(양/음의 상관관계)
# numpy 함수 : np.corrcoef(arr1, arr2)
x = np.array([15, 12, 27, 37, 29])
y = np.array([1, 4, 2, 9, 7])

In [71]:
# 서로 다른 배열 2개를 활용한 상관계수 matrix
# 결과 : 대칭형 매트릭스(대각선을 경계로 상위, 하위 삼각형 중 하나만 해석해도 된다)
# 오른쪽 아래르 향하는 대각선은 자기 자신과의 상관관계(항상 1)
print(x)
print(y)
print(np.corrcoef(x, y))

[15 12 27 37 29]
[1 4 2 9 7]
[[1.         0.72615657]
 [0.72615657 1.        ]]


In [72]:
# numpy에서는 3개요소를 이용한 상관도를 구하는것이 불가능
# 팬더스를 이용하는 경우는 2개씩 짝지은 모든 경우의수를 구해준다
z = np.array([0.3, 0.5, 0.6, 0.8, 1.3])

In [73]:
np.corrcoef(x, y, z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:
# 표준편차 - 전체 기준
# 1) 배열 타입의 메서드 : arr.std()
# 2) numpy 함수 : np.std(arr)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
# 전체
a.std()

2.581988897471611

In [76]:
# 세로축
a.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [77]:
# 가로축
a.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

#### 브로드캐스팅(BroadCasting)

- 서로 다른 구조(shape)를 가진 배열에 대해 연산을 수행할 때 구조를 맞추는 과정
- 배열과 스칼라값 간의 연산
- 배열과 배열 간의 연산
- 브로드캐스팅 규칙 : 축의 길이가 일치하거나 둘 중 하나의 길이가 1인 두 배열에 대해 호환성을 가짐
<img src='img/broadcast.png' width='600' height='400' align='left'>

In [78]:
# 사용할 배열 객체 확인
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [79]:
a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

#### 1. 배열과 값(single value, scala)

- 스칼라 값을 배열의 구조와 동일한 배열로 변형하여 연산 수행

In [80]:
# 구조가 다른 배열간의 연산
# a배열의 모든 요소에 각각 10씩 더하기
a + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [81]:
# 스칼라 -> 배열 변형
# 3행 3열의 구조에 모든 요소가 10인 배열 생성
scalar_arr = np.full_like(a, 10)
np_print(scalar_arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [82]:
a + scalar_arr

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### 2. 서로 다른 구조의 배열

- 행, 열의 최대 길이를 기준으로 구조를 생성한 배열로 변형하여 연산 수행
- 확장된 행, 열에 대해서 기존 배열과 동일한 데이터로 구성

In [83]:
# 1행 4열의 구조에서 1, 2, 3, 4를 값으로 가지는 배열 x 생성
# 4행 1열의 구조에서 1, 2, 3, 4를 값으로 가지는 배열 y 생성
x = np.arange(1, 5).reshape(1, 4)
y = np.arange(1, 5).reshape(4, 1)

In [84]:
np_print(x)
np_print(y)


    type : <class 'numpy.ndarray'>
    shape : (1, 4)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3 4]]

    type : <class 'numpy.ndarray'>
    shape : (4, 1)
    dimension : 2
    dtype : int32
    data : 
 [[1]
 [2]
 [3]
 [4]]


In [85]:
# 배열 X를 동일한 값으로 4행으로 확장한 새로운 배열 생성
# 행 방향으로 배열 추가(세로길이 증가) 메서드 : np.append(arr1, arr2, axis=0)
new_x = np.append(x, x, axis=0)
new_x

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [86]:
# 이걸 다시 4줄로 만들어주세요
new_x = np.append(new_x, new_x, axis=0)
new_x

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [87]:
# 배열 y도 위의 수순대로 4열까지 확장한 새로운 배열로 저장해주세요.
# 열 방향으로(column갯수 증가)배열 추가 메서드 np.append(), 방향 = 1
new_y = np.append(y, y, axis=1)
new_y

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [88]:
new_y = np.append(new_y, new_y, axis=1)
new_y

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [89]:
x + y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [90]:
new_x + new_y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])